#! /bin/sh
#
# nm-set-fallback - mark a network as fallback
#
# Robert Love

BIN=`which gconftool-2`

if [ "x$1" == "x" ]; then
	echo "usage: $0 <network> <true|false>"
	exit 1
fi

if [ "x$2" != "xtrue" -a "x$2" != "xfalse" ]; then
	echo "usage: $0 <network> <true|false>"
	exit 2
fi

KEY="/system/networking/wireless/networks/${1}/fallback"
CURRENT=`$BIN --get $KEY 2>/dev/null`

if [ "x$CURRENT" != "xtrue" -a "x$CURRENT" != "xfalse" ]; then
	echo "Network '$1' is not valid"
	exit 3
fi

$BIN --set --type=bool $KEY ${2}
