#!/bin/sh

# contrib/scripts/checkpatch-git-post-commit-hook:
#   Call this script via ".git/hooks/post-commit"

if [ "$NM_HOOK_DISABLED" = 1 ]; then
    exit 0
fi

FILE=contrib/scripts/checkpatch-feature-branch.sh
if [ -x "$FILE" ]; then
    "$FILE"
    exit 0
fi

FILE=contrib/scripts/checkpatch.pl
if [ -x "$FILE" ]; then
    git format-patch -U65535 --stdout -1 | "$FILE"
    exit 0
fi
