###############################################################################
# examples/C/glib
###############################################################################

examples_C_glib_cppflags = \
	-I${top_srcdir}/shared \
	-I${top_builddir}/shared \
	-I${top_srcdir}/libnm-core \
	-I${top_builddir}/libnm-core \
	-I${top_srcdir}/libnm \
	-I${top_builddir}/libnm \
	$(GLIB_CFLAGS) \
	-DNM_VERSION_MAX_ALLOWED=NM_VERSION_NEXT_STABLE

examples_C_glib_cppflags_gdbus = $(examples_C_glib_cppflags)
examples_C_glib_cppflags_libnm = $(examples_C_glib_cppflags)

check_programs_norun += \
	examples/C/glib/add-connection-gdbus \
	examples/C/glib/add-connection-libnm \
	examples/C/glib/get-active-connections-gdbus \
	examples/C/glib/get-ap-info-libnm \
	examples/C/glib/list-connections-gdbus \
	examples/C/glib/list-connections-libnm \
	examples/C/glib/monitor-nm-running-gdbus \
	examples/C/glib/monitor-nm-state-gdbus

examples_C_glib_add_connection_gdbus_CPPFLAGS = $(examples_C_glib_cppflags_gdbus)
examples_C_glib_add_connection_gdbus_LDADD = \
	$(GLIB_LIBS) \
	$(UUID_LIBS)

examples_C_glib_add_connection_libnm_CPPFLAGS = $(examples_C_glib_cppflags_libnm)
examples_C_glib_add_connection_libnm_LDADD = \
	libnm/libnm.la \
	$(GLIB_LIBS)

examples_C_glib_get_active_connections_gdbus_CPPFLAGS = $(examples_C_glib_cppflags_gdbus)
examples_C_glib_get_active_connections_gdbus_LDADD = \
	$(GLIB_LIBS)

examples_C_glib_get_ap_info_libnm_CPPFLAGS = $(examples_C_glib_cppflags_libnm)
examples_C_glib_get_ap_info_libnm_LDADD = \
	libnm/libnm.la \
	$(GLIB_LIBS)

examples_C_glib_list_connections_gdbus_CPPFLAGS = $(examples_C_glib_cppflags_gdbus)
examples_C_glib_list_connections_gdbus_LDADD = \
	$(GLIB_LIBS)

examples_C_glib_list_connections_libnm_CPPFLAGS = $(examples_C_glib_cppflags_libnm)
examples_C_glib_list_connections_libnm_LDADD = \
	libnm/libnm.la \
	$(GLIB_LIBS)

examples_C_glib_monitor_nm_running_gdbus_CPPFLAGS = $(examples_C_glib_cppflags_gdbus)
examples_C_glib_monitor_nm_running_gdbus_LDADD = \
	$(GLIB_LIBS)

examples_C_glib_monitor_nm_state_gdbus_CPPFLAGS = $(examples_C_glib_cppflags_gdbus)
examples_C_glib_monitor_nm_state_gdbus_LDADD = \
	$(GLIB_LIBS)

###############################################################################
# examples/C/qt
###############################################################################

if WITH_QT

examples_C_qt_cppflags = \
	-I${top_srcdir}/libnm-core \
	-I${top_builddir}/libnm-core \
	-I${builddir}/examples/C/qt \
	$(DBUS_CFLAGS) \
	$(QT_CFLAGS)

check_programs_norun += \
	examples/C/qt/add-connection-wired \
	examples/C/qt/list-connections \
	examples/C/qt/change-ipv4-addresses \
	examples/C/qt/monitor-nm-running

examples_C_qt_add_connection_wired_SOURCES = examples/C/qt/add-connection-wired.cpp
examples_C_qt_add_connection_wired_CPPFLAGS = $(examples_C_qt_cppflags)
examples_C_qt_add_connection_wired_LDADD = \
	$(DBUS_LIBS) \
	$(QT_LIBS)

examples_C_qt_list_connections_SOURCES = examples/C/qt/list-connections.cpp
examples_C_qt_list_connections_CPPFLAGS = $(examples_C_qt_cppflags)
examples_C_qt_list_connections_LDADD = \
	$(DBUS_LIBS) \
	$(QT_LIBS)

examples_C_qt_change_ipv4_addresses_SOURCES = examples/C/qt/change-ipv4-addresses.cpp
examples_C_qt_change_ipv4_addresses_CPPFLAGS = $(examples_C_qt_cppflags)
examples_C_qt_change_ipv4_addresses_LDADD = \
	$(DBUS_LIBS) \
	$(QT_LIBS)

examples_C_qt_monitor_nm_running_SOURCES = examples/C/qt/monitor-nm-running.cpp
examples_C_qt_monitor_nm_running_CPPFLAGS = $(examples_C_qt_cppflags)
examples_C_qt_monitor_nm_running_LDADD = \
	$(DBUS_LIBS) \
	$(QT_LIBS)

examples/C/qt/monitor-nm-running.moc: examples/C/qt/monitor-nm-running.cpp
	$(AM_V_GEN) $(MOC) -i $< -o $@

BUILT_SOURCES += \
	examples/C/qt/monitor-nm-running.moc

endif

EXTRA_DIST += \
	examples/C/qt/add-connection-wired.cpp \
	examples/C/qt/list-connections.cpp \
	examples/C/qt/change-ipv4-addresses.cpp \
	examples/C/qt/monitor-nm-running.cpp

