#!/bin/bash

cat << EOF
# BEGIN RECORD 6.2.0.873-21
iface.initiatorname = iqn.2010-04.org.ipxe:d05faa97-c4be-44f6-a723-efde9aa399a0
iface.transport_name = tcp
iface.hwaddress = 00:33:21:98:b9:f0
iface.bootproto = STATIC
iface.ipaddress = 192.168.6.200
iface.subnet_mask = 255.255.255.0
iface.vlan_id = 123
iface.net_ifacename = eth0
node.name = iqn.2003-01.org.x:disk1
node.conn[0].address = 192.168.6.32
node.conn[0].port = 3260
node.boot_lun = 01000000
# END RECORD
EOF

