#!/bin/bash

set -e

rm -Rf "./ci-build"
mkdir "./ci-build"
cd "./ci-build"

${CHERRY_LIB_MESONSETUP} . "${CHERRY_LIB_SRCDIR}"
${CHERRY_LIB_NINJABUILD}
${CHERRY_LIB_MESONTEST}
# no valgrind tests, since setns(2) is not supported by it
