# Fedora:
#   cadence: every 6 months
#   support: 13 months
# Image aliases: latest, rawhide
# Releases and support info: https://docs.fedoraproject.org/en-US/releases/lifecycle/
# NetworkManager versions info: https://src.fedoraproject.org/rpms/NetworkManager
fedora:
- version: rawhide
  support: yes
  nm: main
- version: 42
  support: 2026-05-13
  nm: 1.52
  tier1-default: yes
- version: 41
  support: 2025-11-19
  nm: 1.50

# CentOS Stream
centos:
- version: stream9
  support: 2027-05-31
  nm: main

# RHEL:
# Even minor versions:
#   cadence: every year
#   support: 2 years EUS + 2 years SAP / Enhaced EUS
# Odd minor versions:
#   cadence: every year (every other 6 months than even versions)
#   support: 6 months
# Releases and support info: https://access.redhat.com/support/policy/updates/errata
rhel:
- version: 9.6  # not released yet
  support: yes
  nm: main
- version: 9.5
  support: yes
  nm: 1.48
- version: 9.4
  support: 2026-04-30
  extended-support: 2028-04-30
  nm: 1.46
- version: 9.2
  support: 2025-05-31
  extended-support: 2027-05-31
  nm: 1.42
- version: 8.10  # last RHEL 8 release, maintenaince support only
  support: 2029-05-31
  extended-support: no
  nm: 1.40
- version: 8.8
  support: 2025-05-31
  extended-support: 2027-05-31
  nm: 1.40
# SAP / Enhaced EUS only:
- version: 9.0
  support: 2024-05-31
  extended-support: 2026-05-31
  nm: 1.36
- version: 8.6
  support: 2024-05-31
  extended-support: 2026-05-31
  nm: 1.36

# Ubuntu:
# LTS:
#   cadence: every 2 years
#   support: 5 years LTS + 5 years extended security
# non-LTS (rolling):
#   cadence: every 6 months
#   support: 9 months
# Image aliases: latest (LTS), rolling (LTS or non-LTS), devel
# Releases and support info: https://salsa.debian.org/debian/distro-info-data/-/blob/main/ubuntu.csv
# NetworkManager versions info: https://packages.ubuntu.com/search?keywords=network-manager
ubuntu:
- version: devel
  support: yes
  nm: main
- version: 25.04
  name: plucky
  support: 2026-01-15
  nm: 1.52
- version: 24.10
  name: oracular
  support: 2025-07-10
  nm: 1.48
- version: 24.04
  name: noble
  support: 2029-05-31
  extended-support: 2034-04-25
  nm: 1.46
- version: 22.04
  name: jammy
  support: 2027-06-01
  extended-support: 2032-04-21
  nm: 1.36

# Debian:
#   cadence: every 2 years
#   support: 3 years + 2 years LTS
# Images aliases: testing, sid, stable, oldstable, oldoldstable
# Releases and support info: https://salsa.debian.org/debian/distro-info-data/-/blob/main/debian.csv
# NetworkManager versions info: https://packages.debian.org/search?keywords=network-manager
debian:
- version: testing
  support: yes
  nm: main
- version: sid
  support: yes
  nm: main
- version: 12
  name: bookworm
  support: 2026-06-11
  extended-support: 2028-06-30
  nm: 1.42
- version: 11
  name: bullseye
  support: 2024-08-15
  extended-support: 2026-08-31
  nm: 1.30

# Alpine:
#   cadence: every 6 months
#   support: 2 years
# Image aliases: latest, edge (development)
# Releases and support info: https://alpinelinux.org/releases/
# NetworkManager versions info (manually select Alpine version): https://pkgs.alpinelinux.org/packages?name=networkmanager&arch=x86_64
alpine:
- version: edge
  support: yes
  nm: main
- version: 3.21
  support: 2026-11-01
  nm: 1.50
- version: 3.20
  support: 2026-04-01
  nm: 1.46
- version: 3.19
  support: 2025-11-01
  nm: 1.44
