#!/bin/bash

CONFIG="$1"

if [ -z "${CONFIG}" ] ; then
    echo $"Usage: ifup <device name>" >&2
    exit 1
fi

usage_and_fail() {
    cat <<EOF >&2
$1!

See all profiles with \`nmcli connection\`.
Reload files from disk with \`nmcli connection reload\`
Activate the desired profile with \`nmcli connection up \"\$NAME\"\`
EOF
    exit 1
}

OLD_IFS="$IFS"

re='^/etc/sysconfig/network-scripts/ifcfg-[^/]+$'
for f in "/etc/sysconfig/network-scripts/ifcfg-$CONFIG" "/etc/sysconfig/network-scripts/$CONFIG" ; do
    [[ "$f" =~ $re ]] || continue
    [ -f "$f" ] || continue

    nmcli connection load "$f" \
    && nmcli connection up filename "$f" \
    && exit 0

    usage_and_fail "Failure to activate file \"$CONFIG\""
done

IFS=$'\n '
UUIDS=( $(nmcli -g connection.uuid connection show "$CONFIG" 2>/dev/null) )
IFS="$OLD_IFS"
if [ "${#UUIDS[@]}" -eq 1 ] ; then
    nmcli connection up uuid "${UUIDS[0]}" \
    && exit 0
    usage_and_fail "Failure to activate profile \"$CONFIG\" (uuid ${UUIDS[0]})"
fi

usage_and_fail "No suitable profile \"$CONFIG\" found"
