#!/bin/bash

# A list of packages useful/needed to build and develop
# NetworkManager on Fedora and RHEL.
#
# Not all of these packages are available, depending
# on your distribution/release. But yum will happily
# skip them.
#
# Not all of these packages are strictly speaking necessary.
# This is a generous list of related packages.

set -xe

DNF="$(which dnf &>/dev/null && echo dnf || echo yum)"

install() {
    if [ "$NM_INSTALL" != "" ]; then
        $NM_INSTALL "$@"
    else
        sudo "$DNF" install -y "$@"
    fi
}

install_ignore_missing() {
    for p; do
        install "$p" || :
    done
}

install \
    ModemManager-devel \
    ModemManager-glib-devel \
    mobile-broadband-provider-info-devel \
    audit-libs-devel \
    bash-completion \
    bluez-libs-devel \
    bzip2 \
    cscope \
    dbus-devel \
    dbus-python \
    dbus-x11 \
    dhclient \
    gcc-c++ \
    gettext-devel \
    git \
    glib2-doc \
    gnutls-devel \
    gobject-introspection-devel \
    gtk-doc \
    intltool \
    iptables \
    jansson-devel \
    libcurl-devel \
    libndp-devel \
    libpsl-devel \
    libselinux-devel \
    libtool \
    libuuid-devel \
    make \
    meson \
    newt-devel \
    nss-devel \
    polkit-devel \
    ppp \
    ppp-devel \
    pygobject3-base \
    python3-dbus \
    python3-gobject \
    qt-devel \
    readline-devel \
    rpm-build \
    systemd-devel \
    teamd-devel \
    vala-devel \
    vala-tools \
    valgrind \
    wireless-tools-devel \
    #end

# some packages don't exist in certain distributions. Install them one-by-one, and ignore errors.
install_ignore_missing \
    python-gobject-base \
    #end
