#! /bin/sh
### BEGIN INIT INFO
# Provides:       NetworkManager
# Required-Start: $network $dbus
# Default-Start:  3 4 5
# Default-Stop:   0 1 2 6
# Description: NetworkManager, a network and wireless connection manager
### END INIT INFO

NETWORKMANAGER_BIN=/opt/gnome/bin/NetworkManager
test -x $NETWORKMANAGER_BIN || exit 5

. /etc/rc.status
rc_reset

case "$1" in
    start)
        echo -n "Starting the NetworkManager"
        startproc $NETWORKMANAGER_BIN
	rc_status -v
        ;;
    stop)
        echo -n "Shutting down the NetworkManager"
        killproc -TERM $NETWORKMANAGER_BIN
	rc_status -v
        ;;
    restart)
        $0 stop
        $0 start
	rc_status
        ;;
    force-reload|reload)
        echo -n "Reloading the NetworkManager"
        killproc -HUP $NETWORKMANAGER_BIN
	rc_status -v
        ;;
    status)
        echo -n "Checking for the NetworkManager: "
        checkproc $NETWORKMANAGER_BIN
        rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|force-reload|reload}"
        exit 1
        ;;
esac

